apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: retail-app
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: gke-app-ksa
      containers:
      - name: backend
        image: IMAGE_TAG_BACKEND
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: retailos-secrets
              key: db-url
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: retailos-secrets
              key: jwt-key
        - name: Jwt__Issuer
          value: "RetailOS.Api"
        - name: Jwt__Audience
          value: "RetailOS.Client"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        args:
        - "--structured-logs"
        - "--private-ip"
        - "--port=5432"
        - "CLOUDSQL_INSTANCE"  # replaced at deploy time
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"




