apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: retail-app
spec:
  progressDeadlineSeconds: 900
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: gke-app-ksa
      readinessGates:
      - conditionType: "cloud.google.com/load-balancer-neg-ready"
      containers:
      - name: frontend
        image: IMAGE_TAG_FRONTEND
        ports:
        - containerPort: 80



