apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-mvp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Youngyz1/retail-mvp
    targetRevision: HEAD
    path: helm/retailos
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
