apiVersion: v2
name: retailos
description: RetailOS — Full-Stack Retail Management System
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - retail
  - management
  - dotnet
  - react
maintainers:
  - name: Youngyz
